name: Api workflow
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/api.yml'
      - 'main.go'
    branches:
      - master

jobs:
  unittest:
    name: Run unit tests
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Run tests
        run: go test

  build:
    name: Build
    needs: [ unittest ]
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build api
        run: go build -o bin/api

      - name: Create artifact
        run: tar -cvf artifact bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: artifact

  deploy:
    name: Deploy production
    needs: [ build ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: .

      - name: Untar artifact
        run: mkdir recipe_api/ && tar -xvf artifact -C recipe_api/

      - name: Prepare env config
        run: |
          echo "${{ secrets.CONFIGS }}" > recipe_api/.env

      - name: Copy project to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: recipe_api/
          target: .

      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: sudo supervisorctl restart recipe_api
