name: App workflow
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build api
        run: go build -o bin/api

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: bin/

  deploy_dev:
    name: Deploy develop
    needs: [ build ]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
        with:
          path: recipe_api_dev/

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: recipe_api_dev/bin/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api_dev/bin/
          target: .

      - name: Prepare env config
        run: |
          echo "${{ secrets.CONFIGS_DEV }}" > recipe_api_dev/.env

      - name: Copy env config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api_dev/.env
          target: .

  deploy:
    name: Deploy production
    needs: [ build ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
        with:
          path: recipe_api/

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact
          path: recipe_api/bin/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api/bin/
          target: .

      - name: Prepare env config
        run: |
          echo "${{ secrets.CONFIGS }}" > recipe_api/.env

      - name: Copy env config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api/.env
          target: .

      - name: Copy supervisor config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: etc/template/recipe_api.conf
          strip_components: 2
          target: /etc/supervisor/conf.d/recipe_api.conf
