name: App workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build -o bin/recipe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: recipe_artifact
          path: bin/

  deploy_dev:
    name: Deploy develop
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recipe_artifact
          path: recipe_api_dev/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api_dev/
          target: .

  promote_prod:
    name: Promote to production
    needs: [deploy_dev]
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recipe_artifact
          path: recipe_api/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api/
          target: .
