name: App workflow
on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        run: go build -o bin/recipe

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: recipe_artifact
          path: bin/

  deploy_dev:
    name: Deploy develop
    needs: [ build ]
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recipe_artifact
          path: recipe_api_dev/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api_dev/
          target: .

  deploy_prod:
    name: Deploy production
    needs: [ build ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: recipe_artifact
          path: recipe_api/

      - name: Copy artifact to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api/
          target: .

      - name: Create config
        run: |
          echo "${{ secrets.CONFIGS }}" > recipe_api/.env

      - name: Copy config to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: recipe_api/.env
          target: recipe_api/
          strip_components: 1
